# Generated by Django 5.0.1 on 2024-09-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_has_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.CharField(blank=True, max_length=10, null=True)),
                ('trouser', models.CharField(blank=True, max_length=10, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='store.product')),
            ],
        ),
    ]
